name: Sign and Verify File

on:
  push:
    branches:
      - main

jobs:
  sign-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Cosign
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/download/v2.4.1/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Sign File
        run: |
          echo "${{ secrets.COSIGN_KEY }}" > cosign.key
          cosign sign-blob --key cosign.key --passphrase "${{ secrets.COSIGN_PASSWORD }}" ./path/to/your/file

      - name: Verify File
        run: |
          cosign verify-blob --key cosign.pub --signature signature.sig ./path/to/your/file
